#!/bin/sh

rsync \
	--archive \
	--verbose \
	--exclude /books \
	--exclude /gis \
	--exclude /movies \
	--exclude /music \
	--exclude /pictures \
	--exclude /reference \
	--exclude /software \
	/home/jfin/* \
	/media/share

rsync \
	--archive \
	--verbose \
	/media/storage/* \
	/media/share
