#!/bin/sh

get_headphones () {
    read -p '(a)irpods or (w)h-1000xm3? ' headphones
    if [ "$headphones" != a -a "$headphones" != w ]
    then
        get_headphones
    fi
}

if [ -z "$1" ]
then
    get_headphones
else
    headphones="$1"
fi

case "$headphones" in
    a) mac="8C:7A:AA:C5:FB:9D" ;;
    b) mac="70:26:05:CF:75:A1" ;;
esac

temp=$(mktemp)
sudo systemctl restart bluetooth.service 
bluetoothctl power on > "$temp"
cat "$temp" | awk '! /^\[/ { print }'
bluetoothctl connect "$mac" > "$temp"
cat "$temp" | awk '! /^\[/ { print }'
