#!/bin/sh

# Reset in case getopts has been used previously in the shell.
OPTIND=1         

# path="$PWD/$1"
path="$2"

trans_path_unix() {
	cygpath "$path"
}

trans_path_win() {
	cygpath -w "$path"
}

trans_path_link() {
	p="${path//file:\/\/\/RB/R:}"
	echo "${p//\%20/ }"
}

trans_path_link

# # opts that have a colon, e.g. w:, have an argument $OPTARG
# while getopts 'wl' opt; do
# 	case "$opt" in
# 		w)  path="$(trans_path_win)"
# 			;;
# 		l)  path="$(trans_path_link)"
# 	esac
# done

# shift $((OPTIND-1))

# # tests for double dash, end of options
# # not needed for this humble incantation
# # [ "${1:-}" = "--" ] && shift

# # printf '%s' "$path" > /dev/clipboard
# echo "$path"
