#!/bin/sh

ffmpeg=/c/Users/jinman/software/ffmpeg/bin
PATH="$ffmpeg:$PATH" youtube-dl\
    --ignore-errors\
    --output "%(playlist_index)s-%(title)s.%(ext)s"\
    --extract-audio\
    --audio-format "mp3"\
    --audio-quality 0\
    "$@"
