#!/bin/sh

if [ "$1" == "." ]
then
	# show only hidden files
	file=$(find -path "*/.*" | fzy)
	shift
else
	# show only non-hidden files
	file=$(find -path "*/.*" -prune -o -print | fzy)
fi

if [ -n "$1" ]
then
	command=$1 
	shift
else
	command=echo
fi

if [ -n "$file" ]
then
	old_dir="$PWD"
	cd "${file%/*}"
	$command "${file##*/}" "$@"
fi

cd "$old_dir"
