#!/bin/sh

summary="$(LC_CTYPE=English\
    /c/Program\ Files/R/R-4.1.2/bin/Rscript.exe \
    $HOME/scripts/get-summary.r)"
echo "Hi Mary,

I worked on these tasks today:

$summary

Have a pleasant evening :)," > /dev/clipboard
