#! /bin/sh
# status bar

# unicode blocks
bar18='\xe2\x96\x81' 
bar14='\xe2\x96\x82' 
bar24='\xe2\x96\x84' 
bar34='\xe2\x96\x86' 
bar44='\xe2\x96\x88' 
shade='\xe2\x96\x91'
# wired='\xF0\x9F\x96\xA7'
# last three are "variation selector"
# https://stackoverflow.com/questions/9626115/color-in-the-unicode-standard
# https://www.utf8-chartable.de/
# https://apps.timwhitlock.info/unicode/inspect?s=%E2%9A%A1
# lbolt='\xe2\x9a\xa1\xef\xb8\x8e'
# lbolt='\xe2\x8c\x81'

# bar items
# network
Net() {
    eth=$(< /sys/class/net/enp6s0/operstate)

    if [ "$eth" != "up" ]
    then
        info=$(< /proc/net/wireless)
        dbm_dot=$(echo "$info" | awk 'FNR == 3 { print $4 }')
        dbm=${dbm_dot%.}
        dbm_if_zero=${dbm:--100}
        sig=$(( 2 * ( $dbm_if_zero + 100 )))
    fi

    if [ "$sig" -eq 0 ]
    then
        modem_path=$(mmcli -L | awk '{ print $1 }')
        modem=${modem_path##*/}
        sig_percent=$(mmcli -m "$modem" | grep signal | awk '{ print $4 }')
        sig_double=${sig_percent%\%}
        if [ "$sig_double" -eq 0 ]
        then
            sig=0
        else
            sig=$(( sig_double / 2 + 50 ))
        fi
    fi

    if [ $eth = up ]
    then
        first="e"
	elif [ $sig -eq 0 ]
    then
        first="_"
	elif [ "$sig" -ge 60 ]
    then
        first="$bar14"
    else
        first="$bar18"
    fi

    if [ $sig -eq 0 ]
    then
        var="${first}___ "
    elif [ $sig -ge 90 ]
    then
        var="$first$bar24$bar34$bar44 "
    elif [ $sig -ge 80 ]
	then
		var="$first$bar24$bar34$bar18 "
	elif [ $sig -ge 70 ]
	then
		var="$first$bar24$bar18$bar18 "
	elif [ $sig -ge 60 ]
	then
		var="$first$bar18$bar18$bar18 "
    else
        var="$first$bar18$bar18$bar18 "
	fi

    echo -e "$var"
}

# battery
Bat() {
	cap=$(< /sys/class/power_supply/BAT0/capacity)
	state=$(< /sys/class/power_supply/BAT0/status)

    # set first char
    if [ "$state" != Discharging ]
    then
        first="c"
	elif [ "$cap" -ge 13 ]
    then
        first="$bar44"
    else
        first="$shade"
    fi

	if [ "$cap" -ge 88 ]
	then
		var="$first$bar44$bar44$bar44 "
	elif [ "$cap" -ge 63 ]
	then
		var="$first$bar44$bar44$shade "
	elif [ "$cap" -ge 38 ]
	then
		var="$first$bar44$shade$shade "
	elif [ "$cap" -ge 13 ]
	then
		var="$first$shade$shade$shade "
	else
        var="$first$(printf "%02d" "$cap")% "
	fi
    echo -e "$var"
    
}

# time
Time() {
	var="$(date '+%a, %b %d, %H:%M')"
	echo "$var" 
}

notify-send "$(Net)$(Bat)$(Time)"
