#!/bin/sh

pw_dir="$HOME/passwords"
account="$1"
pw_path="$pw_dir/$account"

if [ ! -f "$pw_path" ]
then
	pw_path=$(ls -d "$pw_dir"/* | fzy --query="$account")
fi

tail -n 1 $pw_path | tee /dev/clipboard


