#!/bin/sh

links='
    bp basin plan 2019,                 R:\RB3\Shared\Basin Planning\Basin Plan Editions\2019 Basin Plan\2019_basin_plan_r3_complete.pdf
    bp basin planning folder,           R:\RB3\Shared\Basin Planning
    bp basin planning webpage,          https://www.waterboards.ca.gov/centralcoast/publications_forms/publications/basin_plan/
    bp lyris list,                      mailto:reg3_basinplan_triennial@swrcb18.waterboards.ca.gov
    bprt sharepoint,                    https://cawaterboards.sharepoint.com/DWQ/WQSA/SitePages/BasinPlanningRoundtable.aspx?CT=1618447388817&OR=OWA-NT&CID=66fbe96a-8ea2-2186-6f32-b715ceddbf45
    bu viewer,                          https://gispublic.waterboards.ca.gov/portal/apps/webappviewer/index.html?id=116f7daa9c4d4103afda1257be82eb16
    calaters,                           H:\Travel\calaters\gersExc.jnlp
    ilp templates,                      R:\RB3\Shared\Ag-ILRP\2 - Program Management\10 - Accessibility\Templates
    im individual meetings,             H:\Individual Meetings
    im individual meetings local,       /c/Users/JInman/Individual Meetings
    key dates calendar,                 R:\RB3\Shared\- Board Meetings\Executive Assistant\Key Dates Calendar\2023_key_dates_calendar_updated_110722 blue.pdf
    laws and regulations,               https://www.waterboards.ca.gov/laws_regulations/
    paulas accessibility training,      R:\RB3\Shared\Ag-ILRP\2 - Program Management\10 - Accessibility\Accessibility_guidance\Creating Accessible Word Documents\Basic Styles Training
    pay period calendar,                http://waternet.waterboards.ca.gov/das/human_resources/docs/2021_paycalendar.pdf
    sb basin planning wiki,             http://wiki/basinplanning/doku.php?id=start#guidance_for_regional_board_staff
    signed resolutions webpage,         https://www.waterboards.ca.gov/centralcoast/board_decisions/adopted_orders/
    staff report template,              R:\RB3\Shared\- Board Meetings\Current Agenda\Template Staff Report
    tmdl unit folder,                   R:\RB3\Shared\TMDL_Wtrshd Assess\
    tr triennial review webpage,        https://www.waterboards.ca.gov/centralcoast/publications_forms/publications/basin_plan/triennial_review/
    trainings,                          H:\Trainings
    tribal data base,                   https://cawaterboards.sharepoint.com/OPP/TribalDB?e=1%3A6f65d8e93688464fb0242970eac54920
    unit meetings,                      R:\RB3\Shared\TMDL_Wtrshd Assess\_TMDL Program\Meetings\Unit-Program Meetings\FY 21-22
    water boards academy,               https://waterboards.gosignmeup.com/Public/Course/Browse
    work plan status fy 21-22,          R:\RB3\Shared\TMDL_Wtrshd Assess\_TMDL Program\Work Plan\FY21-22\R3_BP-IR-TMDL Workplan_FY21-22_Draft_2021_0318 - status.xlsx
    ocean plan and asbs map,            https://gispublic.waterboards.ca.gov/portal/home/webmap/viewer.html?webmap=ce85c309d07d444e8f5c8126b7acfcb7
    r3 writing guide,                   R:\RB3\Shared\TMDL_Wtrshd Assess\Writing style guides_pete\R3_writing_style_and_conventions.pdf
    r3 wiki,                            http://wiki/r3/doku.php?id=start
	basin plan amendment bp process,    R:\RB3\Shared\TMDL_Wtrshd Assess\Basin Planning\0_BasinPlan_document\basin_plan_amend_process.docx
'

desc=$(echo "$links" | sed 's/ *\(.*\),.*/\1/' | fzy -q "$*")
if [ -z "$desc" ]; then
    exit
fi
link=$(echo "$links" | grep "${desc}," | sed 's/.*, *//')
drive=$(echo "$link" | cut -c1-3)
if [ "$drive" = "/c/" ]; then
    tmux split-window -b -c "$link"
    tmux select-layout main-vertical
else
    cygstart "$link"
fi
