#!/bin/sh

link="$1"
head=$(echo "$link" | cut -c1-4)
if [ "$head" = "http" ] 
then
    ftype="http"
else
    ftype=${link##*.}
fi

case "$ftype" in
    "pdf") command=SumatraPDF ;;
    "http") command=brave ;;
    *) command=cygstart ;;
esac

"$command" "$link" > /dev/null 2>&1 &
