#!/bin/sh

# process options
OPTIND=1
unset new copy todo
while getopts 'n' arg; do
    case "${arg}" in
        n) nodisp=-nodisp ;;
        *) echo unknown option; exit ;;
    esac
done
shift $(( OPTIND - 1))

if [ -d "$1" ]; then
	set "$1"/*
fi

for last; do 
    true
done

trap "pkill ffplay; exit" QUIT
trap "pkill ffplay; read -p 'paused... '" INT

while true; do
    echo playing "${1##*/}"
    ffplay -autoexit $nodisp "$1" > /dev/null 2>&1 &
    wait "$!"
    if [ "$1" = "$last" ]; then
        set $files
    else
        shift
    fi
done

