#!/bin/sh

ffplay=$(cygpath $USERPROFILE/software/ffmpeg/ffplay)

if [ -d "$1" ]; then
	set "$1"/*
fi

for last; do 
    true
done

trap "pkill ffplay; exit" QUIT
trap "pkill ffplay" INT

while true; do
    echo playing "${1##*/}"
    $ffplay -autoexit "$1" > /dev/null 2>&1 &
    wait "$!"
    if [ "$1" = "$last" ]; then
        set $files
    else
        shift
    fi
done

