#!/bin/sh
# add, commit, and push dotfile changes

git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME add -u
git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME commit -m "updates"
git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME push
