#!/bin/sh
# set up new install

# install programs
pacman -Syu --noconfirm

# list generated via "pacman -Qe"
pacman -S --noconfirm --needed\
    base\
    git\
    man-db\
    mksh\
    python\
    python-pip\
    rsync\
    tmux\
    cygutils\
    procps\
    vim

# checkout dotfiles into new home dir
git config --global user.name "John Inman"
git config --global user.email jfinmaniv@icloud.com
git config --global credential.helper store

git clone --bare https://github.com/jfinmaniv/dotfiles $HOME/.dot.git

function dot {
   git --git-dir=$HOME/.dot.git/ --work-tree=$HOME "$@"
}

dot checkout msys

if [ "$?" = 0 ]
then
    echo "Checked out dot files."
else
    mkdir dotfiles.bak
    echo "Backing up pre-existing dot files."
    dot checkout msys 2>&1 \
        | egrep "\s+\." \
        | awk {'print $branch'} \
        | xargs -I{} mv {} dotfiles.bak/{}
fi

dot checkout msys
dot config --local status.showUntrackedFiles no
dot push --set-upstream origin msys

mkdir .vim/{backup,swap,undo}

# terminus font
curl --output terminus.zip https://files.ax86.net/terminus-ttf/files/latest-windows.zip
