#!/bin/sh

check_setting () {
	if [ "$setting" != "up" -a "$setting" != "down" ]; then
		read -p "(u)p or (d)own? " arg
		case $arg in
			u) setting=up ;;
			d) setting=down ;;
			*) check_setting ;;
		esac
	fi
}

setting="$1"
check_setting

wg-quick $setting mullvad-us195
