#!/bin/sh

hour=$1
if [ -z $hour ]
then
    hour=0630
fi

wake_s=$(date --date="today $hour" +%s)
current_s=$(date +%s)
if [ $wake_s -le $current_s ]; then
	waketime=$(date --date="tomorrow $hour" +%Y%m%d%H%M%S)
else
	waketime=$(date --date="today $hour" +%Y%m%d%H%M%S)
fi

sudo rtcwake --date $waketime -m disk
    
pactl set-sink-volume 0 80%

mpv --no-resume-playback \
	$HOME/music/beethoven/quartetto-italiano/late-quartets/op-127-2.mp3

sudo ZZZ
