#! /bin/sh
# status bar

# unicode blocks
bar18='\xe2\x96\x81' 
bar14='\xe2\x96\x82' 
bar24='\xe2\x96\x84' 
bar34='\xe2\x96\x86' 
bar44='\xe2\x96\x88' 
shade='\xe2\x96\x91'

# bar items
# network
Net() {
    sig=none
	if [ "$(ip address show wlan0 | grep 'inet[^6]')" ]
	then
		dbm=$(iw dev wlan0 link | awk '/signal/ { print $2 }')
		sig=$(( 2 * ( $dbm + 100 )))
	fi
    if [ $sig = "none" ]
    then
        var="____ "
    elif [ $sig -ge 90 ]
    then
        var="$bar14$bar24$bar34$bar44 "
    elif [ $sig -ge 80 ]
	then
		var="$bar14$bar24$bar34$bar18 "
	elif [ $sig -ge 70 ]
	then
		var="$bar14$bar24$bar18$bar18 "
	elif [ $sig -ge 60 ]
	then
		var="$bar14$bar18$bar18$bar18 "
    else
        var="$bar18$bar18$bar18$bar18 "
	fi
	echo -e "$var"
}

# battery
Bat() {
	cap=$(< /sys/class/power_supply/BAT0/capacity)
	if [ "$cap" -ge 88 ]
	then
		var="$bar44$bar44$bar44$bar44 "
	elif [ "$cap" -ge 63 ]
	then
		var="$bar44$bar44$bar44$shade "
	elif [ "$cap" -ge 38 ]
	then
		var="$bar44$bar44$shade$shade "
	elif [ "$cap" -ge 13 ]
	then
		var="$bar44$shade$shade$shade "
	else
        var="$shade$shade$shade$shade "
	fi
    echo -e "$var"
}

# time
Time() {
	var="$(date '+%a %m/%d %H:%M') "
	echo "$var" 
}

notify-send "$(Net)$(Bat)$(Time)"
