#!/bin/sh

if [ "$1" = "pull" ]; then
	git_command=pull-repo
elif [ "$1" = "push" ]; then
	git_command=push-repo
fi

repos="\
	$HOME/notes
	$HOME/hours
	$HOME
	$HOME/scripts
	$HOME/todo
	$HOME/reminders
	$HOME/passwords
	"
	
for repo in $repos; do
	echo "$1 ${repo##*/}" | tr '[:lower:]' '[:upper:]'
	$git_command "$repo"
	echo
done

if [ "$1" = "push" ]; then
	shared_notes='/r/RB3/Shared/WQ Control Planning/JI Notes'
	local_agendas=$(cygpath "$USERPROFILE/Individual Meetings")
	echo "SHARE NOTES"
	rsync -av "$HOME/notes/" "$shared_notes"
	rsync -av "$local_agendas" "/h/Individual Meetings"
fi
