#!/bin/sh


set_direction () {
	case "$1" in
		push|s) direction=push ;;
		pull|l) direction=pull ;;
		*) get_direction "$1" ;;
	esac
}
get_direction () {
	if ! echo push s pull l | grep --word-regexp --quiet "$1"; then 
		read -p'pu(s)h or pu(l)l? ' arg
        set_direction "$arg"
        get_direction "$direction"
	fi
}
shared='/r/RB3/Shared/WQ Control Planning/JI Notes'

set_direction "$1"
if [ "$direction" = "pull" ]; then
    echo "dotfiles:"
    git-dot pull
    echo
    echo "scripts:"
    git -C $HOME/scripts pull
    echo
    echo "hours:"
    git -C $HOME/hours pull
    echo
    echo "notes:"
    git -C $HOME/notes pull
    echo
    echo "todo:"
    git -C $HOME/todo pull
    echo
    echo "passwords:"
    git -C $HOME/passwords  pull
    echo
    echo "reminders:"
    git -C $HOME/reminders  pull
elif [ "$direction" = "push" ]; then
    echo "dotfiles:"
    sync-repo -d
    echo
    echo "scripts:"
    sync-repo $HOME/scripts
    echo
    echo "hours:"
    sync-repo $HOME/hours
    echo
    echo "notes:"
    sync-repo $HOME/notes
	git push shared main
	git --git-dir="$shared" --work-tree="$shared" checkout main
    echo
    echo "todo:"
    sync-repo $HOME/todo
    echo
    echo "passwords:"
    sync-repo $HOME/passwords
    echo
    echo "reminders:"
    sync-repo $HOME/reminders
fi
