#!/bin/sh


set_direction () {
	case "$1" in
		push|s) direction=push ;;
		pull|l) direction=pull ;;
		*) get_direction "$1" ;;
	esac
}
get_direction () {
	if ! echo push s pull l | grep --word-regexp --quiet "$1"; then 
		read -p'pu(s)h or pu(l)l? ' arg
        set_direction "$arg"
        get_direction "$direction"
	fi
}

set_direction "$1"
if [ "$direction" = "pull" ]; then
    echo "dotfiles:"
    run-dot-git pull
    echo
    echo "scripts:"
    git -C $HOME/scripts pull
    echo
    echo "work:"
    git -C $HOME pull
    echo
    echo "todo:"
    git -C $HOME/todo pull
    echo
    echo "passwords:"
    git -C $HOME/.passwords  pull
elif [ "$direction" = "push" ]; then
    echo "dotfiles:"
    sync-dot-repo
    echo
    echo "scripts:"
    sync-repo $HOME/scripts
    echo
    echo "work:"
    sync-repo $HOME
    echo
    echo "todo:"
    sync-repo $HOME/todo
    echo
    echo "passwords:"
    sync-repo $HOME/.passwords
fi
