#!/bin/sh

if [ "$1" = "pull" ]; then
	git_command=pull-repo
elif [ "$1" = "push" ]; then
	git_command=push-repo
fi

repos="\
	$HOME/notes
	$HOME/hours
	$HOME
	$HOME/scripts
	$HOME/todo
	$HOME/reminders
	$HOME/passwords
	"
	
for repo in $repos; do
	if [ $repo = $HOME ]; then
		repo_name=dotfiles
	else
		repo_name=$repo
	fi
	echo "$1 ${repo_name##*/}" | tr '[:lower:]' '[:upper:]'
	$git_command "$repo"
	echo
done

if [ "$1" = "push" ]; then
	user_profile=$(cygpath $USERPROFILE)

	echo "SHARE NOTES"
	rsync -av --exclude=".*" "$HOME/notes/" '/r/RB3/Shared/Basin Planning/Temp, JI'
	echo

	echo "BACKUP MUSIC"
	rsync -av "$user_profile/Music/" '/h/Music'
	echo

	echo "BACKUP TEMPLATES"
	rsync -av "$user_profile/Templates/" '/h/Templates'
	echo

	echo "BP REMEDIATION"
	rsync -av "$user_profile/Basin Plan Remediation/" '/r/RB3/Shared/Basin Planning/Basin Plan Remediation'
	echo

	echo "BACKUP AGENDAS"
	rsync -av "$user_profile/Individual Meetings/" '/h/Individual Meetings'
fi
