#!/bin/sh

# set up #######################################################################
red='\033[0;31m'
unred='\033[0m'

# pull #########################################################################
if [ "$1" = "in" ]
then
    unset way
    dir="$PWD"
    cd

    # dotfiles
    echo
    echo "PULLING DOTFILES"
    wrap-git-dot pull

    # scripts
    echo
    echo "PULLING SCRIPTS"
    cd scripts
    git pull

    # waterboard
    echo
    echo "PULLING WATERBOARD"
    cd
    git pull
    cd "$dir"
fi

# push #########################################################################
if [ "$1" = "out" ]
then
    dir="$PWD"
    cd

    # dotfiles
    echo
    echo "PUSHING DOTFILES"
    wrap-git-dot add -u
    wrap-git-dot commit -m updates
    wrap-git-dot push

    # scripts
    echo
    echo "PUSHING SCRIPTS"
    cd scripts
    git add .
    git commit -m updates
    git push

    # waterboard
    echo
    echo "PUSHING WATERBOARD"
    cd
    git add .
    git commit -m updates
    git push
    cd "$dir"
fi

# exit #########################################################################
if [ "$1" != "in" -a "$1" != "out" ]
then
    echo -e "${red}error${unred}: Arg 1 must be 'in' or 'out'."
fi

