#!/bin/sh

git_command=git
git_files=.
git_repo=${1:-.}

# process options
OPTIND=1
while getopts 'd' arg; do
	case "${arg}" in
		d) 
			git_command=git-dot 
			git_files=-u
			git_repo=$HOME/.dotfiles.git
			;;
		*) 
			echo unknown option \"$arg\"
			exit 
			;;
	esac
done
shift $((OPTIND-1))

$git_command -C $git_repo add $git_files
$git_command -C $git_repo commit -m message
$git_command -C $git_repo push
