#!/bin/sh

if [ "$1" = "in" ]
then
    echo -e "Pulling dot repo"
    git-dot pull
    echo -e "\nPulling scripts repo"
    git -C $HOME/scripts pull
    echo -e "\nPulling water board repo"
    git -C $HOME pull
fi

if [ "$1" = "out" ]
then
    echo -e "Pushing dot repo"
    sync-dot-repo
    echo -e "\nPushing scripts repo"
    sync-repo $HOME/scripts
    echo -e "\nPushing water board repo"
    sync-repo $HOME
fi
