#!/bin/sh

# process options
new=false
copy=false
OPTIND=1
while getopts 'nc' arg
do
    case "${arg}" in
        n) new=true ;;
        c) copy=true ;;
        *) return ;;
    esac
done
shift $((OPTIND-1))

# if new note, edit new file and quit when finished
if $new
then
    dayno=$(date +'%y%j')
    i=a
    while [ -e $HOME/notes/${dayno}${i}.txt ]
    do
        if [ $i = "z" ]
        then
            echo "too many notes today"
            return 1
        else
            i=$(echo $i | tr "a-y" "b-z")
        fi
    done
    print -s vim $HOME/notes/${dayno}${i}.txt
    vim $HOME/notes/${dayno}${i}.txt
    return
fi

# otherwise, select file
cd $HOME/notes
match=$(grep -ir "${*:-.}"\
    | sed -e 's/: */:/'\
    | sort -k2\
    | fzy -l20)
file=${match%%:*}
line=${match##*:}
cd "$OLDPWD"

# if none selected, then do nothing and quit
if [ -z "$file" ]
then
    return
fi

# if all we want is the path, then send it to the clipboard and quit
if $copy
then
    print -n $HOME/notes/$file > /dev/clipboard
    return
fi

# edit the selected file
print -s vim $HOME/notes/$file
vim -c "call search(\"$line\")" $HOME/notes/$file
