#!/bin/sh

trash="$HOME/trash"
timestamp=$(date +'%Y%m%d%H%M%S')

for file in "$@"
do
	# rm links
	if [ -h "$file" ]
	then
		rm "$file"
		continue
	fi

	# timestamp duplicates
	name=$(basename "$file")
    if [ ! -e "$trash"/"$name" ]
    then
        mv "$file" "$trash"
    else
        mv "$file" "$trash"/"$name"-"$timestamp"
    fi
done
