#!/bin/sh

# addition vars due to invoking from cron
# more here:
# https://wiki.archlinux.org/title/Desktop_notifications#Usage_in_programing


cap=$(cat /sys/class/power_supply/BAT0/capacity)
if [ $cap -le 10 ]
then
	sudo -u jfin \
		DISPLAY=:0 \
		DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus \
		notify-send "LOW BATTERY"
fi
